### ISSUE TITLE
Firmware update not working

### ISSUE THREAD

**Issue by EdKok** [norbert-walter/Windsensor_Yachta#3]
Board is v2.0
Firmware is v1.18

Device shows 1.20 is available (via internet), button responds with that a message will show after succes but never happens.
Tried via local file from iPad and Android phone. File is seen but after button the browser looses connection after 10 seconds.
Is there anything I’m doing wrong?

**Comment by norbert-walter** [comment]
Attention! The local IP address changed after Update to V1.20 from 192.168.4.1  to 192.168.5.1.

**Comment by EdKok** [comment]
I saw that in the release notes but the update is just not happening. Think there is a reset/reboot after 10 seconds or so and happily connects back to SignalK, still running v1.8

**Comment by norbert-walter** [comment]
Let me look in the software. I want to check the update function.Am 11.08.2024 10:45 schrieb EdKok ***@***.***>:
I saw that in the release notes but the update is just not happening. Think there is a reset/reboot after 10 seconds or so and happily connects back to SignalK, still running v1.8

**Comment by EdKok** [comment]
While being closer to the device it did succeed now.
